apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: d6j28kwnj-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/d6j28kwnj-java-quarkus-gitops